### ISSUE TITLE
Bad interface

### ISSUE THREAD

**Issue by dominicpoeschko** [skunkforce/unified-abstract-dataproducer-template#2]
Bad idea to mix functionaliety here. Add an extra function to give control data to library.

https://github.com/skunkforce/unified-abstract-dataproducer-template/blob/400c8e397318c5193997e7402db53e23b3c35c2e/src/UaDI_template.h#L175

**Comment by bjoekeldude** [comment]
so there should be separate function called `uadi_send_json(device_handle, chunk_ptr)`
I will add that to the interface
